### ISSUE TITLE
reserved scala words within properties leads to compile errors

### ISSUE THREAD

**Issue by arron-green** [eikek/sbt-openapi-schema#105]
i was testing out this plugin and had a case where a field was defined as `type` which lead to a compile time error.  

I'm open to some potential workarounds or a possible fix by wrapping fieldNames with backticks

```
    Example:
      description: example
      properties:
        type:
          type: string
```

which could generate as the following

```
case class(`type`: String)
```
