### ISSUE TITLE
NPE in Parser

### ISSUE THREAD

**Issue by rkazanova** [eikek/sbt-openapi-schema#114]
Trying to setup last version of plugin and I have 
`
sbt:ev-scala> last openapiCodegen
[error] java.lang.NullPointerException
[error] 	at com.github.eikek.sbt.openapi.impl.Parser$.parse(Parser.scala:18)
[error] 	at com.github.eikek.sbt.openapi.OpenApiSchema$.generateCode(OpenApiSchema.scala:107)
`

in build.sbt I have:
`
import com.github.eikek.sbt.openapi._
enablePlugins(OpenApiSchema)
openapiSpec := (Compile/resourceDirectory).value/"ev-api.yaml"
openapiTargetLanguage := Language.Scala
`

in project/plugins.sbt `addSbtPlugin("com.github.eikek" % "sbt-openapi-schema" % "0.8.1")`

**Comment by eikek** [comment]
Hi @rkazanova , does this happen only with 0.8.1? iow, the same openapi.yml worked with a previous version?

**Comment by rkazanova** [comment]
I have tried with 0.8.0 too. didn't try with the older versions.

**Comment by eikek** [comment]
Ok thank you! Can you share the openapi - or best the part that triggers the error only? The plugin doesn't support every use case, it could be that there is something defined which is not supported.

**Comment by rkazanova** [comment]
will check it and send it back. will try to use the simple thing first

**Comment by eikek** [comment]
This yml lacks any data structure. So there is nothing to generate. Or is this not the complete file?

**Comment by eikek** [comment]
You may look at [this example](https://github.com/eikek/sbt-openapi-schema/blob/master/plugin/src/sbt-test/openapi-test/json-scala/src/main/resources/test.yml) - the `components` section defines the data structures. And these definitions (only these) are used by this plugin. All other parts of the yml are ignored.

**Comment by rkazanova** [comment]
It was not completed YAML. I mean I cut a lot to send a small one. With your example, it works. I will check what exactly in my YAML  throws an error

**Comment by rkazanova** [comment]
It seems that it doesn't like enums:
```
  schemas:
    Event:
      required:
        - name
        - startDate
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        eventType:
          type: string
          description: Event type
          enum:
          # Store calendar events:
          - CLOSING_DAY # Also used in supplier calendar
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        stopAllocation:
          type: object
          description: "Optional time period during which to stop the allocation for \"Store Closing\" events."
          properties:
            start:
              type: string
              format: date
            end:
              type: string
              format: date
          required:
            - start
            - end
        stopReplenishment:
          type: object
          description: "Optional time period during which to stop replenishment for \"Store Closing\" events."
          properties:
            start:
              type: string
              format: date
            end:
              type: string
              format: date
          required:
            - start
            - end
        eventStatus:
          type: string
          description: Event status
          enum:
            - ACTIVE
            - PLANNED
            - DRAFT
            - CANCELED
            - EXECUTED
```
